const express = require("express");
const mongoose = require("mongoose");
const app = express();

// let demoData = [{'email': 'bhattimarisha18@gmail.com',
//   'views': "I am very lucky to have met you in my 1st week on campus...cuz I can't imagine surviving here without you for more than 10 days EVER!!!",
//   'user': 'Sakshi Kaushal'},
//  {'email': 'bhattimarisha18@gmail.com',
//   'views': 'I feel very lucky to have met you. Thank you for always being there to talk to whenever I needed someone.',
//   'user': 'Vatsalya'},
//  {'email': 'bhattimarisha18@gmail.com',
//   'views': 'Knock knock cutie,  cheers to all our rants and talk, forever grateful to have you♥️,  thank you for everything literally?♥️,  such a warm person?',
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'bhattimarisha18@gmail.com',
//   'views': " bold, confident,  and good with words as you are. Thank you for always being there❤️ I'll miss our gossip sessions xD",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'asatipragya.11@gmail.com',
//   'views': "Could not have survived KGP without her. She means the world to me. KGP gave me my Best Friend and I'm so grateful for it.",
//   'user': 'A Chetan Gowda'},
//  {'email': 'mahimaarya162@gmail.com',
//   'views': 'The only regret I have is not meeting you sooner?❤️,  love you and forever grateful to have you, cheers to us',
//   'user': 'Bethala Rajavardhini'},
//  {'email': 't.deepikasravya@gmail.com',
//   'views': 'Deepu deepika you are always the besty',
//   'user': 'Mausam'},
//  {'email': 'sanjurithvik@gmail.com',
//   'views': 'Anna Dancer asalu ! Great Mahesh Babu Fan??. Stop procrastinating man?',
//   'user': 'Penukonda Yeshwanth'},
//  {'email': 'sanjurithvik@gmail.com',
//   'views': 'Aaagam macha ?',
//   'user': 'Mummadi Nikhil'},
//  {'email': 'neilpratap2016@gmail.com',
//   'views': 'Hooman',
//   'user': 'Poola Sai Prapul Reddy'},
//  {'email': 'neilpratap2016@gmail.com',
//   'views': 'Sometimes I think that talking to a wall is better.',
//   'user': 'Anandapu Dheeraj'},
//  {'email': '1289nav@gmail.com',
//   'views': "The only thing that didn't change in my 5 years of KGP is U n ME. KGP without you I can't imagine. Thanks for everything My Showoff Alien Tom ?",
//   'user': 'Pinninti Renu Sree'},
//  {'email': 'aditiraj2000@gmail.com',
//   'views': 'hi cutie!',
//   'user': 'Aakriti Gupta'},
//  {'email': 'pal.ankit.6762@gmail.com',
//   'views': "I have never met anyone as hardworking as you bhai!!\n\\nKudos to all those late-night singing and deep-talk sessions :')\n\\nThank you jaaneman <3",
//   'user': 'Pranit Mukundrao Mendhe'},
//  {'email': 'pal.ankit.6762@gmail.com',
//   'views': 'Hi,  Anki you are a friend that everyone deserves!! You are so genuine,  authentic,  and fun to be with, ',
//   'user': 'Saumya Prabhakar'},
//  {'email': 'renusree1237@gmail.com',
//   'views': "Thannkuuu for everything ??♥️,  cheers to all the times we've spent together, our card games, life talks, and everything love you?♥️",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'smritijain79@gmail.com',
//   'views': 'Hi,  I hope you know that you are one of my favourite people. Thanks for taking care of me and protecting me always,  you are such a great friend!',
//   'user': 'Sakshi Kaushal'},
//  {'email': 'saumya.prabhakar2123@gmail.com',
//   'views': 'Yo Saumi,  years flew away just like that. Never seen someone so mature,  enduring and affectionate. Glad you were around !',
//   'user': 'Ankit Pal'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': "I got really lucky in the lucky draw. Best roomie everrr. Thank you itne saare weird songs se introduce karvane ke liye xD. I'll miss you!",
//   'user': 'Anjali Meena'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': "You're amazing Sakshi! We've had the most random discussions yet somehow they were meaningful. Thanks for being there,  let's talk more! Miss you",
//   'user': 'Haasita Pinnepu'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': "I hope you'll never discover google maps and rely on Boots,  Maps and Bag-pack. Thanks for sharing all my highs and lows at KGP.",
//   'user': 'Rohit Jain'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': "The most genuine person I've met in KGP. Thank you for listening to my rants and always being there for me whenever I needed someone to talk to.",
//   'user': 'Vatsalya'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': "Our experiences are so precious. I am lucky to have you in life. Rarely people meet someone on day 1 of college vibe so well,  it's scary!",
//   'user': 'Marisha Bhatti'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': 'Thank you for everything cutest sakshi♥️,  literally everything,  cheers to all our booktalks and life lessons,  forever grateful to have met you?,  literally everything,  cheers to all our booktalks and life lessons,  forever grateful to have met you?',
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'sakshikaushal567@gmail.com',
//   'views': 'You are probably one of the realest,  no-nonsense friend I have made here. Cheers to the good times! btw,  I really like your writing',
//   'user': 'Deogade Sanyukta Bipin'},
//  {'email': 'ark.gouri1310@gmail.com',
//   'views': "Has faced BT repeatedly but has always come out on top! Her resilience is something that I've never seen nor would ever see again,  will miss you",
//   'user': 'Varun Balakrishna'},
//  {'email': 'aakriti16.iitkgp@gmail.com', 'views': '2002', 'user': 'Aditi Raj'},
//  {'email': 'vinodnayakj.321@gmail.com',
//   'views': 'Hey bro idk u but marry my roomie i really wanna attend ur wedding, Hehe',
//   'user': 'Hehe'},
//  {'email': 'sesettyssvardhan@gmail.com',
//   'views': 'Vardhan raawwwwwwwwwwwwwww........ topuuu rawwwww..........',
//   'user': 'Suvvada Rishi'},
//  {'email': 'balakrishna.varun@gmail.com',
//   'views': 'known for the Varun Rice. \n\\nLoves food,  and your best biryani pal',
//   'user': 'Sri Gouri Rajaram'},
//  {'email': 'bhawna.julia060@gmail.com',
//   'views': 'Hieeeee miss you churaillll',
//   'user': 'Mausa.'},
//  {'email': 'rishisuvvada@gmail.com',
//   'views': 'OP ACTOR!!!',
//   'user': 'Venkataseetharam Manoj Malipeddi'},
//  {'email': 'deogadesanyukta@gmail.com',
//   'views': 'You are the most non-problematic person I know...and anyone who has a problem with you needs medical attention. You are the sweetest ?',
//   'user': 'Sakshi Kaushal'},
//  {'email': 'deogadesanyukta@gmail.com',
//   'views': "I'll just say this,  if anyone has a problem with you,  they have a problem with me,  cause how can anyone have a problem with you!",
//   'user': 'Marisha Bhatti'},
//  {'email': 'deogadesanyukta@gmail.com',
//   'views': "What I can say,  nothing would've been possible without you in all these final days,  forever ever grateful and indebted to have you♥️♥️?",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'g.chantikishore@gmail.com',
//   'views': 'The chill maamu ?',
//   'user': 'Mummadi Nikhil'},
//  {'email': 'pinnepu.haasita@gmail.com',
//   'views': "We have come a very long way from 1st yr staircase conversation to where we are right now! Sfm wouldn't have been possible without you. Thanks?",
//   'user': 'Sakshi Kaushal'},
//  {'email': 'pinnepu.haasita@gmail.com',
//   'views': 'Thanks for being there. Love you. Will miss you a lot ?.',
//   'user': 'Sakshi Kaushal'},
//  {'email': 'anuragparvathgari7@gmail.com',
//   'views': 'U r d besthing evr hpnd 2 me @ d mos unexpctd tym. TQ 4 being born. Poor boy,  u cant escape from me now :) letsgrowold2gether and cherish life<3',
//   'user': 'Mekala Nischala'},
//  {'email': 'v.saigokul@gmail.com',
//   'views': "Dont grab your brother's room.",
//   'user': 'Mandavilli Pragnay'},
//  {'email': 'divyangnasharma16@gmail.com',
//   'views': 'Bestest machli',
//   'user': 'Parth Jindal'},
//  {'email': 'divyangnasharma16@gmail.com',
//   'views': 'Bestest',
//   'user': 'Parth Jindal'},
//  {'email': 'divyangnasharma16@gmail.com',
//   'views': "Never would have thought I'd make my best friend and partner in all fun sad happy times for life. To infinitely more experiences together,  2.2 ?",
//   'user': 'Parth Jindal'},
//  {'email': 'alishaparvez1@gmail.com',
//   'views': 'Hey,  genial encyclopedia! I hereby encourage you to talk to more introverts :))',
//   'user': 'Varshitha P'},
//  {'email': 'lakshmi15900@gmail.com',
//   'views': 'True definition of aagam and attitude. Konchem monditanam and alagadam manu ra ?. Keep irritating others until they shout on you (?)',
//   'user': 'Penukonda Yeshwanth'},
//  {'email': 'lakshmi15900@gmail.com',
//   'views': 'Jyothi and his leelalu ?',
//   'user': 'Mummadi Nikhil'},
//  {'email': 'devrajpriyadarshi01@gmail.com',
//   'views': 'You are the sweetest. Thanks for being there for me always.? I would need more f1 gossip from you,  and will give other gossips in return. Deal?',
//   'user': 'Sakshi Kaushal'},
//  {'email': 'harshavardhanputta5@gmail.com',
//   'views': 'skinny bitch (jk) ?... dedication pro max...',
//   'user': 'Mummadi Nikhil'},
//  {'email': 'pragnan.kool79@gmail.com',
//   'views': 'hii',
//   'user': 'Nadimatla Pragnan'},
//  {'email': 'ujn1504@gmail.com',
//   'views': 'One of the best person I met in kgp. Be it academic,  social,  entertainment,  sports or anything.',
//   'user': 'Harsh Prakash'},
//  {'email': 'jemappelleharsh@gmail.com',
//   'views': 'UPSC machake!',
//   'user': 'Suryadeep Mandal'},
//  {'email': 'jadhavrohith08@gmail.com',
//   'views': 'You are the person whom I always wanted in my life,  lobe u from ee dept',
//   'user': 'Biswashree Roy'},
//  {'email': 'parthjaiswal13@gmail.com',
//   'views': "Paarth! Thanks for making sure I don't get lost on kgp roads,  and thanks for everything else. Will miss you a lot sheesh! ?",
//   'user': 'Sakshi Kaushal'},
//  {'email': 'shrijanidhali42291@gmail.com',
//   'views': 'Bruh,  we are twins,  looks se aur harkaton se bhi! Lots of love!',
//   'user': 'Gargi Das'},
//  {'email': 'luvkhoiwal10@gmail.com',
//   'views': 'Male Sea Horse anatomy',
//   'user': 'Ayush Khandelwal'},
//  {'email': 'anjalimeena1000@gmail.com',
//   'views': "Wouldn't have survived college without you. You are the most talented person I know & I wish I could be as organised as you. I am scared of you.",
//   'user': 'Marisha Bhatti'},
//  {'email': 'anjalimeena1000@gmail.com',
//   'views': "Cutie pie anjali,  thank you for everything, for all the times we've spent together??♥️,  forever grateful to have you all,  you're such a sweet ♥",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'anjalimeena1000@gmail.com',
//   'views': "You are the only person in campus who has ever scolded me,  and that's big! Also,  tereko allowed hai daantna lol. Love you always ?",
//   'user': 'Sakshi Kaushal'},
//  {'email': 'riya21april@gmail.com',
//   'views': 'Dear co-owner of the one braincell that helped us survive college,  you are the only person on this planet more weird than me & that says a lot!',
//   'user': 'Marisha Bhatti'},
//  {'email': 'riya21april@gmail.com',
//   'views': 'You are very innocently dirty lol,  I love it! Seriously though,  you are extremely fun to be around.',
//   'user': 'Sakshi Kaushal'},
//  {'email': 'riya21april@gmail.com',
//   'views': "Cutest maitri,  thanku you everything,  for all the times we've spent together ?♥️?",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'riya21april@gmail.com',
//   'views': "Sweetest person maitri, cheers to all the times we've spent together",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'riya21april@gmail.com',
//   'views': "Very effortlessy funny, sweet, self destructive & not-so-innocent insaan.I'll miss you and all the ranting and gossip. Also",
//   'user': 'Anjali Meena'},
//  {'email': 'himmatramkaraghav@gmail.com',
//   'views': 'One of the first friends I made in kgp. Finance god. Thoda party/treat bhi diya karo sir.',
//   'user': 'Harsh Prakash'},
//  {'email': 'shivamkumarshu@gmail.com',
//   'views': 'Cheeeeku h tu',
//   'user': 'Yogendra Panwar'},
//  {'email': 'shivamnayak5apr@gmail.com',
//   'views': 'Wish you a very sucess in your future endeveours',
//   'user': 'Sagar Suman'},
//  {'email': 'shivamnayak5apr@gmail.com',
//   'views': 'Wish you a very success in your future endeveours',
//   'user': 'Sagar Suman'},
//  {'email': 'shachijalote@gmail.com',
//   'views': 'You were my closest friend in kgp,  also the most caring,  smart and fun person I know. I hope you never lose your infectious postive vibe. Atb!',
//   'user': 'Dhruv Rai'},
//  {'email': 'goyalaarsh18@gmail.com',
//   'views': 'Lazyass,  thanks for sticking around in thick and thin. Milne ka plan banao bc,  Catan khelenge!',
//   'user': 'Ankit Pal'},
//  {'email': 'sravanigopi2002@gmail.com',
//   'views': 'Will you forgive me and unblock...',
//   'user': 'Sanket Pramodkumar Jaiswal'},
//  {'email': 'prathamnarwade444@gmail.com',
//   'views': 'Ek aur peg bnao bhai....',
//   'user': 'Aseem Anand'},
//  {'email': 'yeshwanth2002@gmail.com',
//   'views': 'Mana JCB dancing star ✨',
//   'user': 'Mummadi Nikhil'},
//  {'email': 'manusanivaishnavi.iitkgp@gmail.com',
//   'views': "Thannkuuu for everything ??♥️,  cheers to all the times we've spent together, our card games, life talks, and encouraging me in everything ?you?",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'manusanivaishnavi.iitkgp@gmail.com',
//   'views': 'From A stranger in line to neighbor,   to partner in crime & cards & cook,  now to a beautiful part of my life? A promise to be forever with you?',
//   'user': 'Pinninti Renu Sree'},
//  {'email': 'rhea2801@gmail.com',
//   'views': 'Will you clarify what happened and unblock me...',
//   'user': 'Sanket Pramodkumar Jaiswal'},
//  {'email': 'pranitmendhe30@gmail.com',
//   'views': 'Selfless',
//   'user': 'Ankit Pal'},
//  {'email': 'sagar18052002@gmail.com',
//   'views': 'Best friend from the department. Thanks for all the help in online sem?. Aage bhi machate raho aur hame bhul mat jana.',
//   'user': 'Harsh Prakash'},
//  {'email': 'sagar18052002@gmail.com',
//   'views': "It's fun talking politics with bro. You have to turn all your devices off so that you don't end up in jail.",
//   'user': 'Manish Kumar Das'},
//  {'email': 'sagar18052002@gmail.com',
//   'views': 'bro naya laptop khareed le',
//   'user': 'Manish Kumar Das'},
//  {'email': 'harshprakash32@gmail.com',
//   'views': 'One of the kindest and most helpful guy I have met in my KGP life. Chess god,  har sport mein talented,  quick-witted and overall badhiya banda.',
//   'user': 'Ujwal Nitin Nayak'},
//  {'email': 'pulkitchauhan03@gmail.com',
//   'views': 'Extreme Machau banda. Very helpful in educational field,  baki field me bhi aisa hi ban jawo?',
//   'user': 'Harsh Prakash'},
//  {'email': 'ayankumar2000@gmail.com',
//   'views': 'Extremely dedicated to the study. I am lucky to know and be a friend of you. MIT me bhi aise hi machana ✌️',
//   'user': 'Harsh Prakash'},
//  {'email': 'sourishsana@gmail.com',
//   'views': 'Good Guy',
//   'user': 'P Anurag Reddy'},
//  {'email': 'sourishsana@gmail.com',
//   'views': 'Thankss for coming to banglore <3 kalsi anurag life ni aadukundaam mumbai nunchi.. liver jaagratha :)',
//   'user': 'Mekala Nischala'},
//  {'email': 'sourishsana@gmail.com',
//   'views': 'The cool kid',
//   'user': 'Periyavaram Sathwik Reddy'},
//  {'email': 'saraalim2001@gmail.com',
//   'views': 'Hi cutie!',
//   'user': 'Aakriti Gupta'},
//  {'email': 'katravathvasu000@gmail.com',
//   'views': 'Your are the best thing I have found in KGP,  thanks for everything. May all your dreams come true',
//   'user': 'Tippagudisi Deepika Sravya'},
//  {'email': 'vatsalya.rajaram@gmail.com',
//   'views': 'You are the sweetest most innocent person I know,  never change. And most importantly I admire how intelligent and hardworking you are!',
//   'user': 'Marisha Bhatti'},
//  {'email': 'vatsalya.rajaram@gmail.com',
//   'views': "You are extremely sweet and caring. You have helped me a lot in a lot of places,  I'm extremely grateful for that. Love you. Will miss you a lot.",
//   'user': 'Sakshi Kaushal'},
//  {'email': 'rohit.mahatme@gmail.com',
//   'views': 'Mahatme bhai,  the ultimate roommate/ padosi/ wingman I could ever have around. Milne ka plan bana bc! Tujhe bhand karaunga :)',
//   'user': 'Ankit Pal'},
//  {'email': 'ranabirbasu12@gmail.com',
//   'views': 'Thanks for being the best thing that happened to me :)',
//   'user': 'Purva Agrawal'},
//  {'email': 'shivamjain7598@gmail.com',
//   'views': 'Brother!',
//   'user': 'Navonil Natta Barman'},
//  {'email': 'sreeyachidere@gmail.com',
//   'views': 'Thanks for everything ?♥️,  metallurgy will not be same without you??, forever grateful to have you',
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'rajavardhinibethala98@gmail.com',
//   'views': 'Thank you sm for being my friend. Listening to my useless worried rants. You are one of the kindest person I have ever met. ❤️. Wishing you happ',
//   'user': 'Deogade Sanyukta Bipin'},
//  {'email': 'rajavardhinibethala98@gmail.com',
//   'views': 'Screaming,  crying,  cooking,  ranting,  ranting, enjoying,  thanks for always being my Comfort place ? Thanks for always being my Teddy bear ?',
//   'user': 'Pinninti Renu Sree'},
//  {'email': 'rajavardhinibethala98@gmail.com',
//   'views': "Momma for a reason!Thank you for everything & you are the sweetest, kindest, most caring person I've known ❤️I will miss youu and the chakralus xD",
//   'user': 'Anjali Meena'},
//  {'email': 'rajavardhinibethala98@gmail.com',
//   'views': 'You share your birthday with my dad,  but you were my momma in college. You are the most nonchalant yet caring,  loving person I have known!',
//   'user': 'Marisha Bhatti'},
//  {'email': 'rajavardhinibethala98@gmail.com',
//   'views': 'Raju momma you are the best! You are my favourite,  and will always be! Also,  cut wierd people out of your life... please!',
//   'user': 'Sakshi Kaushal'},
//  {'email': 'sahitya34@gmail.com',
//   'views': "Forever indebted to have you, cheers to all those times we've spent together,  thank you for everything♥️?, last summer was the bestest?",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'thanuyounger@gmail.com',
//   'views': 'Thanks for everything ?♥️,  metallurgy will not be same without you??, forever grateful to have you, forever grateful to have you, ',
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'nikhilmummadi5762@gmail.com',
//   'views': 'The master of comedy and dark humour in the gang ??',
//   'user': 'Penukonda Yeshwanth'},
//  {'email': 'nikhilmummadi5762@gmail.com',
//   'views': 'My partner in crime,  stay well!! Will meet you again,  as your roommate in hell....',
//   'user': 'Aseem Anand'},
//  {'email': 'vaish1202navi@gmail.com',
//   'views': 'One said "asset & funding liq"&another explained it.Soo enjoyed final yr, with the bday treat, cardio-cycling to class, u banging my door & running',
//   'user': 'Varshitha P'},
//  {'email': 'kowshikkumar2704@gmail.com',
//   'views': 'This man truly shines,  always rising to the occasion,  mostly at night(ha ha...) His unwavering support and positive aura are unbelievable.',
//   'user': 'Kasturi Gnanaguna Sagar'},
//  {'email': 'kowshikkumar2704@gmail.com',
//   'views': 'He truly shines,  always rising to the occasion,  often at night?. His unwavering support and positive aura are unbelievable.',
//   'user': 'Kasturi Gnanaguna Sagar'},
//  {'email': 'gowrimohanagondi@gmail.com',
//   'views': 'Ankhon ko bandh kar jab tum ko dekha.. jo tum ho usse bhi pyaara dekha? Thanks for being 3 of spades in my life ? too precious to lose',
//   'user': 'Pinninti Renu Sree'},
//  {'email': 'gowrimohanagondi@gmail.com',
//   'views': "Thannk for everything ??♥️,  cheers to all the times we've spent together, our card games, life talks, and everything?♥️, such a sweet soul you ar",
//   'user': 'Bethala Rajavardhini'},
//  {'email': 'koyenabasu@gmail.com',
//   'views': 'Hi with the intention of talking for hours about AoT and all our weird conspiracy theories. Really just a healing presence in my life',
//   'user': 'Deogade Sanyukta Bipin'},
//  {'email': 'ramanetanaya@gmail.com',
//   'views': 'WEST WISHES!! \n\\n-Gurjot',
//   'user': 'Gurjot Singh'},
//  {'email': 'kshitiz975@gmail.com',
//   'views': 'Chacha of the Pelu Gang',
//   'user': 'Patel Manthan Shaileshkumar'},
//  {'email': 'dhruv.rai2001@gmail.com',
//   'views': 'G!',
//   'user': 'Prashant Jangid'},
//  {'email': 'sivarishirich@gmail.com',
//   'views': 'I love you. Thanks for coming to my life and making my college days i deserved to enjoy',
//   'user': 'Biswashree Roy'},
//  {'email': 'sivarishirich@gmail.com',
//   'views': 'Mummmaaa miss you mummmaa',
//   'user': 'Mausam'},
//  {'email': 'audumbarchinchkar@gmail.com',
//   'views': 'Very sensible,  extrovert and kind person if you know him closely.Will never forget those never ending discussions/debates?. Machate raho✌️',
//   'user': 'Harsh Prakash'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': 'Hi Mok !',
//   'user': 'Ajitesh Bharti'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': "Hello Moksh....All the best for the life ahead. Stay happy and know that I'll be here when you need me. Apka priya dost...Prakhar",
//   'user': 'Prakhar Singh'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': "Hlo stupid, u'll always be the same to me! I miss those days when we go/bunk the classes together(mostly bunk obv).But yes lets keep gng on trips",
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': 'You sweetest bb (not really). I miss our dancing together at parties, gd. "Kitida navyane tula aathvave dolyatle pani navyane wahave" Me rn :(',
//   'user': 'SAMYUKTA'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': 'Modaaaa,  1st year te last year kahi nahi badalal..Tevha pn tuch roast vhaychi ani aata pn? Anyways,  thanks for being such a "गोड" friend, ATB<3',
//   'user': 'Tanmay Malatkar'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': 'Most honest friend,  best secret keeper...may we be closest forever,  and please always forget to say goodbye,  I never want to hear it from you<3.',
//   'user': 'Ajitesh Bharti'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': 'Hey Moksh, \n\\nYou are the most sweetest person i met at kgp....I love spending time ...talking,  shopping with you....Stay the same forever....<3, ',
//   'user': 'Vaishnavi Pandey'},
//  {'email': 'mokshjadhav2002@gmail.com',
//   'views': 'Heyyy bb <3... missing all those bitching sessions in SN-hallway,  late night ka rona dhona everything i loveee uu kk',
//   'user': 'Kirti Choudhary'},
//  {'email': 'saipragun@gmail.com',
//   'views': "Hello bro... All the best for the future...I'll never forget the support that you gave me at my worst times (uk when). \n\\nThank you for it ??",
//   'user': 'Prakhar Singh'},
//  {'email': 'saipragun@gmail.com',
//   'views': "Ik u are gay for me bro,  but don't be shy,  but gay apart,  apni vibe bohot match krti thi bhai,  and I still lead you in seep,  miss you brOO...",
//   'user': 'Ajitesh Bharti'},
//  {'email': 'saipragun@gmail.com',
//   'views': 'I love u brother anthee ,  manam kalvakapothe life normal ga undipothunde,  kalsi life ne crazy ga marchamm',
//   'user': 'Gugulothu Anvesh Naik'},
//  {'email': 'saipragun@gmail.com',
//   'views': 'Hi Pragya!, I miss the old times,  mostly 4th-5th sem. bs ab Bangalore aaja jldi...Stay the way you are,  happy & brainless-idiot person XD ~Rosie',
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'saipragun@gmail.com',
//   'views': 'hii bb,  u r the core of my (kgp) -life,  ur support,  presence made everything 1000x better,  u r the best thing happened to me in kgp <3',
//   'user': 'Kirti Choudhary'},
//  {'email': 'hritikawasthi14@gmail.com',
//   'views': 'You are a sweetheart. Keep acing your fashion game like you do! Love. Always.',
//   'user': 'Ayushi Saha'},
//  {'email': 'vanshikasahu225@gmail.com',
//   'views': 'Cutiee & a Great friend,  coincidences made us friends,  will miss you a lot <3.',
//   'user': 'Bhagyashree Sharma'},
//  {'email': 'gsampuraktalukdar@gmail.com',
//   'views': 'You guys at Azad were some of the best peeps I have met in life...May we have more trips,  treats and movie nights together in our journey ahead',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'abhishek.agrawal3101@gmail.com',
//   'views': "Hey captain! You're one of the best people I've met and worked with in kgp. I'm going to miss our fights and bickering a lot!",
//   'user': 'Saumili Jana'},
//  {'email': 'gunjanmeena111@gmail.com',
//   'views': "Thank you for being an awesome friend and listening to all my turmoils...Don't take too much load and keep marching forward!",
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'pallavibha318@gmail.com',
//   'views': 'Funn gal. Koi aesa hai jo tujhse baat krke smile nhi krta? Ab hall me koi msti hi nhi krta single room sunsan lgta h. Jldi mil pagal. I miss u♥️',
//   'user': 'Ankita'},
//  {'email': 'pallavibha318@gmail.com',
//   'views': 'Pallu the cutie,  crop top ke alawa kuch pehen lo?, And thoda kam ashleel baatein kiya karo?',
//   'user': 'Pooja'},
//  {'email': 'praneetavanumu@gmail.com',
//   'views': "Sweetest person....\n\\n Don't forget to keep a smile on your face all the time",
//   'user': 'Vishal Erukala'},
//  {'email': 'abinandhan2003@gmail.com',
//   'views': 'Mr. Weightlifting champion making us proud everywhere you participate ??. Will miss you raa',
//   'user': 'Vallakonda Alekhya'},
//  {'email': 'abinandhan2003@gmail.com',
//   'views': 'Broo what ra ur leaving so soon will miss you ra lets party to the fullest one day !!',
//   'user': 'Shivani'},
//  {'email': 'abinandhan2003@gmail.com',
//   'views': 'Abbiii.. U\'re already leaving ah?. I\'m not able to digest. Idek how I\'m gonna survive without u.. Now don\'t ans "with food nd o2"?.will miss u',
//   'user': 'Manu'},
//  {'email': 'abinandhan2003@gmail.com',
//   'views': 'Hey ra mokka fellow',
//   'user': 'Hehe'},
//  {'email': 'samala.raghavendra06@gmail.com',
//   'views': 'Rags will miss you ra lets catchup in hyd ni dance edo oka roju viral chestha ?',
//   'user': 'Shivani'},
//  {'email': 'samala.raghavendra06@gmail.com',
//   'views': 'Rags you are the most kind hearted person I ever met please stay the same. Actual ga nen abaddal aadatam maaneddam ankunna,  this will be my last',
//   'user': 'Marada Susanth'},
//  {'email': 'samala.raghavendra06@gmail.com',
//   'views': 'Ragss! Yo! Will miss u ra! Cricket,  badminton,  intern stress..anni kalisi share cheskunnam! Every year Sankranti ki intiki vachey inka!',
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'sarthak.dholpur@gmail.com',
//   'views': 'This man right here loves technicality,  loves numbers,  but is the laziest,  most procrastinating person I have ever seen in my life. Love you!',
//   'user': 'Madhavan Premrajka'},
//  {'email': 'aayushipriya68@gmail.com',
//   'views': 'TextCheck',
//   'user': 'Mayank Garg'},
//  {'email': 'aayushipriya68@gmail.com',
//   'views': 'Hello Hi',
//   'user': 'Mayank Garg'},
//  {'email': 'aayushipriya68@gmail.com',
//   'views': 'cutie of the gang | gossip bank',
//   'user': 'Poloju Jahnavi'},
//  {'email': 'aayushipriya68@gmail.com',
//   'views': 'hi ra aayushi the psuedo telugu gorl',
//   'user': 'Merugu Rishitha'},
//  {'email': 'sreeswakshareddy25@gmail.com',
//   'views': 'Hey bb,  lub u and miss you a lottttt <3. I miss our goss sesh. My lovely dancing partner haha. Come fas fas to kgp :3',
//   'user': 'SAMYUKTA'},
//  {'email': 'srikiranchandrakkd866@gmail.com',
//   'views': 'Best supporter for life. Always keep smiling',
//   'user': 'Vishal Erukala'},
//  {'email': 'atcikss9@gmail.com', 'views': 'Hello Hi', 'user': 'XYZ youKnowMe'},
//  {'email': 'rishithamerugu@gmail.com',
//   'views': 'Gadida',
//   'user': 'Poloju Jahnavi'},
//  {'email': 'vaishnavipandey17ald@gmail.com',
//   'views': 'Hi vaish !!!\n\\nYou are so annoying ;-; \n\\nChota pack bada dhamakaaaa!!!',
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'vaishnavipandey17ald@gmail.com',
//   'views': 'Hii Vaish…stay happy and chirpy and enjoy the life ahead and also take care. (Also don’t worry abt ur height ?). All the best ?',
//   'user': 'Prakhar Singh'},
//  {'email': 'vaishnavipandey17ald@gmail.com',
//   'views': 'And stop sending me one word reply,  nhi toh I will hate you.',
//   'user': 'Ajitesh Bharti'},
//  {'email': 'vaishnavipandey17ald@gmail.com',
//   'views': "Cute little Jerry, Times were good when listening to ur rants would make my day better.. I kinda miss that. I'll be there for you <3",
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'vaishnavipandey17ald@gmail.com',
//   'views': 'My closest one,  and the worst photographer',
//   'user': 'Ajitesh Bharti'},
//  {'email': 'tripathipranjal75@gmail.com',
//   'views': 'My years at KGP have been one of the most enriching chapters of my life!',
//   'user': 'Kumar Pranjal Tripathi'},
//  {'email': 'harshitpatel7117@gmail.com',
//   'views': 'GD kb krwa raha bhai???',
//   'user': 'Shiva Kumar'},
//  {'email': 'manosij4@gmail.com',
//   'views': 'It was a nice journey with you here in KGP. Our bond will grow stronger. Druheen-nightouts are the best memories. Prem hok tor,  Love you Bhai.',
//   'user': 'Sayan Sarkar'},
//  {'email': 'snehamajumder2002@gmail.com',
//   'views': 'You are a wonderful woman even if you do not believe it. You make people (like me) very comfortable and its been awesome knowing you! Love you.',
//   'user': 'Ayushi Saha'},
//  {'email': 'snehamajumder2002@gmail.com',
//   'views': 'Snehaa brooo... Thank you for being a great co-head and an even more awesome friend... Please get a little less drunk!! Cheers!',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'tusharsachdeva1111@gmail.com',
//   'views': 'Padhai vadhai karo IAS yas bano',
//   'user': 'Lakshya Ghunawat'},
//  {'email': 'sumitchaudhari942@gmail.com',
//   'views': 'Hi sumyaa !! Lavkr bhet yaar... i miss stms,  pn mi tuzi roasting bilkul miss nahi krt ;-; All the best for future.. Take care',
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'abhinavsen2002@gmail.com',
//   'views': 'One of the smartest bong-tamil-punjabi ik! Comical expressions,  sweetest voice & philosophy me PhD',
//   'user': 'Archit Mangrulkar'},
//  {'email': 'arekhani5@gmail.com',
//   'views': 'The most loyal guy on campus. Man literally supports Barca & United to death. 10/10 shaadi material',
//   'user': 'Archit Mangrulkar'},
//  {'email': 'atulyaankitsharma@gmail.com',
//   'views': 'Hi Holland resident. I hope you stay happy and fun like you are. Aur rant thoda kam kiya kar',
//   'user': 'Sharannya Ghosh'},
//  {'email': 'aarshasaiboppudi@gmail.com',
//   'views': 'nee jaathi k***** d*****',
//   'user': 'Marada Susanth'},
//  {'email': 'aarshasaiboppudi@gmail.com',
//   'views': 'naa life gudisipodaniki nen yentha kaaranam nuvv kooda anthe kaaranam',
//   'user': 'Marada Susanth'},
//  {'email': 'cghosh828049@gmail.com',
//   'views': 'Hey my Linux expert buddy. Stay prepared to get technical queries on Whatsapp at odd hours. Jk,  you are a great guy! Stay in touch',
//   'user': 'Sharannya Ghosh'},
//  {'email': 'cghosh828049@gmail.com',
//   'views': 'So glad I found my best friend in you',
//   'user': 'Sarita Singh'},
//  {'email': 'jaswanthcjk@gmail.com',
//   'views': 'You are just amazing ra mustoda',
//   'user': 'Rameshwar'},
//  {'email': 'grdrdasari02@gmail.com',
//   'views': 'ayya naa runa maafi chesthe baguntadi',
//   'user': 'Marada Susanth'},
//  {'email': 'deepsikhabehera2811@gmail.com',
//   'views': 'Always bubbling with energy,  high maintenance emotional drama New York kudii. Looking forward to BLR Drunksikha stories',
//   'user': 'Archit Mangrulkar'},
//  {'email': 'deepsikhabehera2811@gmail.com',
//   'views': 'You surpassed my expectations,  wish we spent more time together T_T; good luck for the future.',
//   'user': 'Mihir Mallick'},
//  {'email': 'azadnrt2002@gmail.com',
//   'views': 'Ekkada unna sare inka every January ki dates fix chesesko!! Pakka pakka rooms lo lemu kani year ki okasari oke intlo undam!will miss our clgdays',
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'sushanthmarada@gmail.com',
//   'views': 'Rey chala miss ayitha anuko kani mari ekuva feel kakuanyway stay in touch koncham ammayilatho matldam nerchuko standards maintain chey(if any?)',
//   'user': 'Shivani'},
//  {'email': 'sushanthmarada@gmail.com',
//   'views': "Mee dance ki pedda fans sir memu?. Asal continuous ga ala ela punches vesthavo. I really enjoy being around u guys. Let's stay in touch :)",
//   'user': 'Manasa'},
//  {'email': 'sushanthmarada@gmail.com',
//   'views': 'Neku Naku ivvani enduku le gaani...ilane kalustu undu prathi sari..mana relation college kanta mundhe start ayyindi..manaki teliyaledu anthey',
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'sushanthmarada@gmail.com',
//   'views': 'Enthaina nee pakka room lo undi...Abbas Abbas ani pilavadam miss avtunna! Sarley...',
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'sushanthmarada@gmail.com',
//   'views': 'Meee hair style,  mee walking style ,  mee dressing style naku pichi,  anyways kalsindi bymistake gaa,  kani kalsundham kavali anii my brother',
//   'user': 'Gugulothu Anvesh Naik'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': 'Mokshadajadhav',
//   'user': 'Vaishnavi Pandey'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': 'One of the few friends jinse milna kam baar hua but dosti tagdi bani rhi and aage bhi rhegi',
//   'user': 'Muskan Kumari'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': "All the very best for your future. I'll never forget the support you've given me. You're the best best companion anyone can ever ask for.",
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': 'Banda tou sahi h but thoda sa chu*** h. All the best for your future buddy. ?',
//   'user': 'Priyanshu Raj'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': "Hlo bro,  thanks for everything u did(uk what)maybe my last 2yrs would have been diff if u didn't..those cycle lifts in the rain!Aah will miss it",
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': 'Saale text kyun ni karta mereko! Chill maar,  I love you anyway bro.',
//   'user': 'Sharannya Ghosh'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': "Hey prakhar,  Humhare bahut kam baat hoti but you are among my first friend's here hope it continues.....All the very best for your future. Tc:)",
//   'user': 'Vaishnavi Pandey'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': '3 puff paas bhai,  next kb tell tell. Fuse on rkha kr bhai,  Taylor km suna kr',
//   'user': 'Ajitesh Bharti'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': 'You made me a better person..Without u,  I wouldnt have survived kgp life..thnks for all the love, support & care..u r the best..be happy always!!',
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'prakhar4660@gmail.com',
//   'views': "hi mc bc, thanks for being such a good friend, wouldn't have survived that cdc wala phase without u. u made blr a lively place ",
//   'user': 'Kirti Choudhary'},
//  {'email': 'prerit.paliwal007@gmail.com',
//   'views': "Not your average Mr.Noida crackhead. Profs don't like you,  missing u;-;",
//   'user': 'Archit Mangrulkar'},
//  {'email': 'sarita01.ar@gmail.com',
//   'views': 'Best person I met at kgp',
//   'user': 'Chirag Ghosh'},
//  {'email': 'sharannyaghosh31@gmail.com',
//   'views': 'Tu bhi kaha text krti h! But koi na bahot zindagi bachi h abhi. Be in touch and take care. All the best and lots of love my friend ?',
//   'user': 'Prakhar Singh'},
//  {'email': 'sharannyaghosh31@gmail.com',
//   'views': 'brooo i love u ..u r such a cute barbiee,  not the reel wala barbie but the real life one,  who can do whatever she want, hmesha ase hi rhna <3',
//   'user': 'Kirti Choudhary'},
//  {'email': 'vb8987850@gmail.com',
//   'views': 'Aur bhai kya haal chaal, Paneer ki sabji achi banata h bhai tu ?, Phle dep mate ab flatmate ?, Cheers to good times brother',
//   'user': 'Prakhar Singh'},
//  {'email': 'archit.mangrulkar@gmail.com',
//   'views': 'The true REAL ONE out there!!!',
//   'user': 'Ashish Rekhani'},
//  {'email': 'www.arnepallijahnavi@gmail.com',
//   'views': 'The bestestest person I met in KGP. My constant stress buster and go to person. Never hesitated to share anything. Tq & lub u <3. #GG TVD FRNDS.',
//   'user': 'Polu Sreenidhi'},
//  {'email': 'www.arnepallijahnavi@gmail.com',
//   'views': 'The bestestest person I met in KGP. Always my stress buster and go to person. Never hesitated to gossip and share. Tq & lub u <3 #GG TVD FRNDS.',
//   'user': 'Polu Sreenidhi'},
//  {'email': 'www.arnepallijahnavi@gmail.com',
//   'views': 'A person with whom I can crack jokes and vibe like a mad person. And sometimes can do a serious conversation.',
//   'user': 'Pulicherla Yasaswinee Harshitha'},
//  {'email': 'krishnchate121@gmail.com',
//   'views': 'My best friend,  and most favorite person in KGP. I wish all your dreams come true. Stay happy :)',
//   'user': 'Bhagyashree Sharma'},
//  {'email': 'snehithreddy888@gmail.com',
//   'views': 'Delhi weather yela undi tammudu..',
//   'user': 'Marada Susanth'},
//  {'email': 'srikar.gidugu7@gmail.com',
//   'views': 'Times change. Dark circles are constant',
//   'user': 'Chirag Ghosh'},
//  {'email': 'shrutijayewar123@gmail.com',
//   'views': 'In a short time,  we became best friends,  sharing countless memories. Cherishing our time together,  I hope for this bond to last forever?.',
//   'user': 'Devarakonda Jyothi Eswar'},
//  {'email': 'darakirti@gmail.com',
//   'views': "Gave one only to pull the other away (ukwim). All the best for the life ahead and let's be there for each other whenever needed ?.",
//   'user': 'Prakhar Singh'},
//  {'email': 'darakirti@gmail.com',
//   'views': 'Hey KK !!\n\\nI love you KK,  \n\\nBye KK .\n\\n(baki milkr baat krte lol)',
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'darakirti@gmail.com',
//   'views': "Hey Panda! If my KGP life was a book of 1000pages,  you'd be a part of 990 pages of them.Thanks for sharing the best moments of our lives with me",
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'darakirti@gmail.com',
//   'views': 'Lucky me for having sbse BKC n nautanki baaj bestie like U Kichu. Aise hi meri RR aur bakwaas sunte rehna zindagi bhar,  comedy aur BKC k sath.',
//   'user': 'Saurav Deshmukh'},
//  {'email': 'darakirti@gmail.com',
//   'views': 'Smart and caring?Sure, but only when needed. Acts tough but is a softie inside xd.Lots of love from my end.Wish you luck vro.144 chars too less:/',
//   'user': 'Uddipan Das'},
//  {'email': 'darakirti@gmail.com',
//   'views': 'U think a testimonial is enough?,  you shaped my campus life bro,  what I was and what you made me,  only a sister can,  love you loads bro...',
//   'user': 'Ajitesh Bharti'},
//  {'email': 'darakirti@gmail.com',
//   'views': 'Hi there,  We had our ups and downs but you have a very special place in my heart,  I hope you know that. Stay in touch! I love you,  sistaa!',
//   'user': 'Sharannya Ghosh'},
//  {'email': 'darakirti@gmail.com',
//   'views': "Hello,  my one and only best friend. Made lot of memories with you (good,  bad,  worst). I wish things were different but life's really unfair uk.",
//   'user': 'Prakhar Singh'},
//  {'email': 'darakirti@gmail.com',
//   'views': "I won't write pages on you bro like someone?, but thanks for always being there in my worst times,  u are the best therapist and best racist bro.",
//   'user': 'Ajitesh Bharti'},
//  {'email': 'mukilsenthil@gmail.com',
//   'views': '17 years and more to go!!',
//   'user': 'Rithick Prabakar'},
//  {'email': 'potturujahnavi29@gmail.com',
//   'views': "The most kind-hearted and selfless person I've ever met. Thanks for always being there to listen to my boring speeches. To many more 2.2s!",
//   'user': 'Yogendra Ajay'},
//  {'email': 'potturujahnavi29@gmail.com',
//   'views': 'Thanks for hearing all my rants. And maybe do a bit less dumb stuff in the future :)',
//   'user': 'Shubham Kulkarni'},
//  {'email': 'meghanalakshmip@gmail.com',
//   'views': "To the one who is there to help ALWAYS,  while your quirks test my patience but it's fun to watch others' getting tested,  never ending debates <3",
//   'user': 'Arnepalli Jahnavi'},
//  {'email': 'meghanalakshmip@gmail.com',
//   'views': 'A caring and supportive person,  sharing room with you has been dramatic and fun,  will never forgot any of our debates and YOU.',
//   'user': 'Pulicherla Yasaswinee Harshitha'},
//  {'email': 'yasaswinee2003@gmail.com',
//   'views': 'hi',
//   'user': 'Pulicherla Yasaswinee Harshitha'},
//  {'email': 'yasaswinee2003@gmail.com',
//   'views': 'In a short time,  we became best friends,  sharing countless memories. Cherishing our time together,  I hope for this bond to last forever?.',
//   'user': 'Devarakonda Jyothi Eswar'},
//  {'email': 'yasaswinee2003@gmail.com',
//   'views': 'To the one whom I can share every secret,  mad ideas,  and silly gossips without shame—true partner in crime. No judgment,  just endless laughter!!',
//   'user': 'Arnepalli Jahnavi'},
//  {'email': 'nn.9350.nn@gmail.com',
//   'views': 'Grateful for our unique bond.Rainy start, cherished memories, unwavering support.Wishing you success, happiness, and crossed paths ahead.',
//   'user': 'Nadimatla Pragnan'},
//  {'email': 'shubhamkulkarni1401@gmail.com',
//   'views': 'I knew it!! You are tru ge',
//   'user': 'Rithick Prabakar'},
//  {'email': 'shubhamkulkarni1401@gmail.com',
//   'views': 'The coolest, smartest and sweet friend one can ever find. I am very thankful to having meet you here :)',
//   'user': 'Potturu Jahnavi'},
//  {'email': 'tanishq142000@gmail.com',
//   'views': 'TT tera bestie tujhe bohot yaad krta h.Thanks for always being with us.Kam time spend krke bhi humesha special rhega tu.Take care of your liver♥',
//   'user': 'Ankita'},
//  {'email': 'tusharkmr15@gmail.com',
//   'views': "I can't even imagine how my days would have been without you homies...May we plan to have more trips,  treats and movie nights ;)",
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'ajay617181@gmail.com',
//   'views': "Always smiling,  open-minded and top of the class! A true friend and down-to-earth soul.Keep shining,  you're the best buddy anyone could ask for!",
//   'user': 'Potturu Jahnavi'},
//  {'email': 'anjaliraj25022002@gmail.com',
//   'views': "Minimum 30 treats are pending,  I've lost count now ?. Pls send the total amount to my account ASAP",
//   'user': 'Aniket Dey'},
//  {'email': 'rathidhruv04@gmail.com',
//   'views': 'Dhruvvv the Gawddd.... Thanks buddy for being such a great co-head,  may our paths cross often in the journey ahead,  Cheers!',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'thatsmeayushi@gmail.com',
//   'views': 'A girl with few words but lots of emotions.Hope tu thora jada khul jae life me, it will help a lot.Good experience with you',
//   'user': 'Muskan Kumari'},
//  {'email': 'thatsmeayushi@gmail.com',
//   'views': "Gurl I just adore you so much.You're so sweet and humble,  but you never had the sutta that u promised",
//   'user': 'Sneha Majumder'},
//  {'email': 'nikithakodipaka1@gmail.com',
//   'views': 'The egoless person on earth after me',
//   'user': 'Bolla Vardhan'},
//  {'email': 'manasgajendra1305@gmail.com',
//   'views': 'One piece is real',
//   'user': 'Rithick Prabakar'},
//  {'email': 'varshita13matcha@gmail.com',
//   'views': 'You are my constant companion and an amazing gossip partner. I will miss you.',
//   'user': 'Ayushi Saha'},
//  {'email': 'sreenidhipolu@gmail.com',
//   'views': 'Sometimes cute sometimes mad sometimes pig.. overall a best friend in campus?',
//   'user': 'Vishal Erukala'},
//  {'email': 'sreenidhipolu@gmail.com',
//   'views': 'My biggest enemy in the campus ?',
//   'user': 'Bandaru Sri Naga Akhil'},
//  {'email': 'sreenidhipolu@gmail.com',
//   'views': 'To the one person who understands all my jokes,  will never forget our movie nights,  fights abt tvd chars,  late night Maggi sessions & chitchats!',
//   'user': 'Arnepalli Jahnavi'},
//  {'email': 'rishikiran1103@gmail.com',
//   'views': "Hey rishi big fan been in love with you since 2 years i didn't get a chance to know you but i really love you and I'll miss you soo much",
//   'user': 'Hehe'},
//  {'email': 'rishikiran1103@gmail.com',
//   'views': "Hey buchki will miss u soo much pakkaga i hope u move on fast? and be happy. I hope you'll be cute forever. Love you. Happy future!!!!!!",
//   'user': 'Reyy'},
//  {'email': 'rishikiran1103@gmail.com',
//   'views': 'Ekkadi nundo regular ga na room ki vachevadivi! Alane ekkada unna sare every year intiki vachey mama! Will miss u!',
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'rishikiran1103@gmail.com',
//   'views': 'ippatikina complan taagadam start chey...',
//   'user': 'Marada Susanth'},
//  {'email': 'bsnakhil26@gmail.com',
//   'views': '#best buddy in campus',
//   'user': 'Vishal Erukala'},
//  {'email': 'reddysurendra294@gmail.com',
//   'views': 'Topper of the BATCH,  topper of the DEPARTMENT,  topper of the CAMPUS,  topper of the WORLD #gold_medal_student',
//   'user': 'Bandaru Sri Naga Akhil'},
//  {'email': 'anamitranew@gmail.com',
//   'views': "From school to college and soon to a new city,  we have come a long way. Can't wait to make it longer! P.S. 10 years of friendship is close.",
//   'user': 'Ayushi Saha'},
//  {'email': 'shivampandeyvg@gmail.com',
//   'views': 'bhaiyo mai bhai apna Pandey bhai !\n\\nHard Fact: Teko zindagi mai kabhi chutkara nahi mil raha merese ?',
//   'user': 'Pooja'},
//  {'email': 'ab20smruti@gmail.com',
//   'views': '• Butter Half - Successfully changed your first love from food to me and 5 sachets of sugar to no sugar coffee ?',
//   'user': 'Pooja'},
//  {'email': 'gouravks.iitkgp@gmail.com',
//   'views': '2nd yr se abhi wala gourav wayyy different+good hai. Yaad aati h teri ab koi opinions hi nhi mangta. Love how you value my rakhi. Best brother?',
//   'user': 'Ankita'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': 'Love you loads babee!\n\\nCan even imagine a day without u in the campus of these 2 years. Hoping for our future together! Umah??',
//   'user': 'Shivani'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': 'Big fan of ur sense of humour ra anvesh. Will really miss u. Hand cricket lo nen ninnu duckout chesa gurthunchuko?',
//   'user': 'Manasa'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': 'Bujiiii love you ra chala edupu osthundi I really wish natho undipo forever marchipolenu iyi 2 years manam spend cheshina time ???',
//   'user': 'Shivani'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': 'Bye annu baby will miss for sure nduk ante aa shivi dobbuthune untadi nga. Plz na gold chain vadiley sincere request',
//   'user': 'Hehe'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': 'Rey na pilla jagratha ?. Nen nin asal miss avvan ra....jus kiddin will miss you lotsss anvesh☺️',
//   'user': 'Vallakonda Alekhya'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': "Lucky to have you as a friend and my roomie. My brother! I wish we'll share this bond throughout our life! Thanks for making me laugh.",
//   'user': 'Kolli Sai Pragun'},
//  {'email': 'anveshg.1312@gmail.com',
//   'views': 'Time management nee daggara nerchkovali anna',
//   'user': 'Marada Susanth'},
//  {'email': 'aryanrane1000@gmail.com',
//   'views': 'Aryan! Thanks for always being there for me,  through all my ups & specially downs. You are really a brother,  always protecting me. Meet soon!,  through all my ups & specially downs. You are really a brother,  always protecting me. Meet soon!',
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'shristishrinet2601@gmail.com',
//   'views': 'Shristi cutie you will always be veryyyy close to my heart…you were person I could share anything with. I miss you soo much,  let’s meet soon',
//   'user': 'Vanshika Prakash'},
//  {'email': 'tmalatkar14@gmail.com',
//   'views': 'Will be forever my brossss. Always the best person to go for life advice. He is super super talented btw. Missing you a lottttttt <3',
//   'user': 'Samyukta Kagdelwar'},
//  {'email': 'tmalatkar14@gmail.com',
//   'views': "Tanya! Life's always been best,  happy & laughable when you were around. Thank you for your true friendship &love. Always be the best as you are!",
//   'user': 'Jadhav Mokshada Nandkumar'},
//  {'email': 'tmalatkar14@gmail.com',
//   'views': "Tanmayyyyyyyy you beautiful,  sweet soul!! 10/10 the most wonderful friend/companion/co-governor <3 KGP is not the same without you :')",
//   'user': 'Nish'},
//  {'email': 'shrivastavabhisha@gmail.com',
//   'views': 'And the best Didi award goes to *Drumrollss* Abhishaa!! Thank you for being a part of my KGP journey',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'archanameherabcd31.05.2000@gmail.com',
//   'views': 'Mast ladki hai,  introvert logo ko bhi extrovert bana deti hai, bring joy in group wherever she is , nice to meet such girl in KGP',
//   'user': 'Bajaj Anirudha Rajendraprasad'},
//  {'email': 'aryan.swain2408@gmail.com',
//   'views': "Hi Babe. I loved my time here at KGP with you and I love you. I've made so many memories with you and I hope I can keep making more. <3, Sampara Ila Grace Victoria",
//   'user': 'Sampara Ila Grace Victoria'},
//  {'email': 'ayushman.iitkgp2020@gmail.com',
//   'views': 'The man born with Ashirvad. He mastered inaction. His life proved right choices at right timing trumps over greater efforts.',
//   'user': 'Arunava Sarkar'},
//  {'email': 'bajajanirudha@gmail.com',
//   'views': 'Such a helpful and wonderful guy! Lucky to have a friend like him. Will miss you dude.....',
//   'user': 'Archana Meher'},
//  {'email': 'bajajanirudha@gmail.com',
//   'views': 'Bajajjj....You are za best...Thank you for standing by me in all the difficult time... May our path cross more often so we can play more TT',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'ganvirsayali@gmail.com',
//   'views': 'Oye sayala mukbang dekhna band kar,  chup chap chal amigos jaldi se ..mich u ?',
//   'user': 'Pooja'},
//  {'email': 'ganvirsayali@gmail.com',
//   'views': "Dear Sayali,  I seriously don't know how I'll survive one more year in the department without you. I'm going to miss you a lot!",
//   'user': 'Saumili Jana'},
//  {'email': 'ganvirsayali@gmail.com',
//   'views': 'Kya krungi m 1saal yha? Teri sath kiya timepass,  tera room,  teri vibe,  pure din ke baad sukoon ki baatein,  miss everything about you. Love you!.',
//   'user': 'Ankita'},
//  {'email': 'himadri.pandya2@gmail.com',
//   'views': "Hima you made this sad little place ICONIC. I owe some of my most personality-defining experiences to you. Campus hasn't been the same w/o you.",
//   'user': 'Nish'},
//  {'email': 'rithickprabakar@gmail.com',
//   'views': 'Stop being ge pls',
//   'user': 'Shubham Kulkarni'},
//  {'email': 'rithickprabakar@gmail.com',
//   'views': 'Thank you for everything. I hope you cherished our bond as much as I did. May the winds conspire more adventures of us together :)',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'kushallkandagatla123@gmail.com',
//   'views': 'Hey mowaaaa!! I had a very best time with you in the campus. Will misss you lotsss mowaa. Nen cheppede crct nuv chesevi anni tappu adi anthe?',
//   'user': 'Vallakonda Alekhya'},
//  {'email': 'saisarangv2002@gmail.com',
//   'views': '4 years and more to come.',
//   'user': 'Rithick Prabakar'},
//  {'email': 'madihahanifa91@gmail.com',
//   'views': "You're strong. You're majestic. You're gorgeous. You're iconic. I'll write stories about your time here in KGP and read them to my kids.",
//   'user': 'Nish'},
//  {'email': 'muskankumari3067@gmail.com',
//   'views': "Made some beautiful memories as roommates with you! Here's to many more! <3",
//   'user': 'Ayushi Saha'},
//  {'email': 'muskankumari3067@gmail.com',
//   'views': 'Hello dost...aage ke corporate majdoor jeevan ke liye all the best. ye dosti hm nhi todenge....?',
//   'user': 'Prakhar Singh'},
//  {'email': 'aditiujjain8@gmail.com',
//   'views': 'Ye ek social butterfly hai.',
//   'user': 'Chirag Ghosh'},
//  {'email': 'aditiujjain8@gmail.com',
//   'views': 'Nothing but a true mother figure :)) Thank you for taking care of all of us <3',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'aditiujjain8@gmail.com',
//   'views': 'no',
//   'user': 'Rithick Prabakar'},
//  {'email': 'alekhyavallakonda@gmail.com',
//   'views': 'Dengutha plz fix date time and place',
//   'user': 'Vishnu'},
//  {'email': 'alekhyavallakonda@gmail.com',
//   'views': 'Crazy energetic dancer chalaaa miss iythaaa nanu kuda Nuvu miss avu na papa ni vadileyi',
//   'user': 'Anvesh'},
//  {'email': 'alekhyavallakonda@gmail.com',
//   'views': 'Love you lekh..',
//   'user': 'Huhu'},
//  {'email': 'alekhyavallakonda@gmail.com',
//   'views': "Baaaabe... Idk nuv lekunda 5th yr chaala boring untundi. Nenu shivi movies chusthu untam mostly?. U're the best,  cute person I have ever known.",
//   'user': 'Manu'},
//  {'email': 'alekhyavallakonda@gmail.com',
//   'views': 'Stress buster and kind hearted Freind , I feel everyone in their life should have freind like you .I hope this friendship doesn’t ends here……',
//   'user': 'Rajashekar Reddy'},
//  {'email': 'alekhyavallakonda@gmail.com',
//   'views': 'Will miss you soo much there is no better friend i can get in the campus,  ur my go to person on the campus and will always lasts forever love u',
//   'user': 'Shivani'},
//  {'email': 'abh1sh3kk14@gmail.com',
//   'views': 'Thank you for being such a sweet and kind friend to me,  best Gsec we could have ever asked for <3',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'aditipasi03102001@gmail.com',
//   'views': 'HELLLLLOOOOOOO',
//   'user': 'Abhisha Shrivastava'},
//  {'email': 'aditipasi03102001@gmail.com',
//   'views': 'Aditiiiii ...Yayyyy.... High 5... Thank you for being in the KGP journey from start to end. May we meet again and have fun',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'snehaarisetti@gmail.com',
//   'views': 'Hi Garal. I love spending time with you and we made so many memories at KGP. I love you  :). I really hope we stay sisters all our lives. <3.',
//   'user': 'Sampara Ila Grace Victoria'},
//  {'email': 'athulpm645@gmail.com',
//   'views': 'Abdboom72 coming soon :)',
//   'user': 'Shubham Kulkarni'},
//  {'email': 'anandayush.kgp@gmail.com',
//   'views': 'You are the best person on campus I have met,  always just 1 call away even at late at night. Thanks for taking soo much care of me, I miss youu',
//   'user': 'Vanshika'},
//  {'email': 'vaibsvikas9@gmail.com',
//   'views': 'The banker guy who will keep you waiting till lunch!!',
//   'user': 'Ishan Gupta'},
//  {'email': 'bhushantny1@gmail.com',
//   'views': 'Brother can multitask and still top the exam with one night preparation!!',
//   'user': 'Ishan Gupta'},
//  {'email': 'bishalkumar8486@gmail.com',
//   'views': 'its about time everyone knows you are gay',
//   'user': 'Rithick Prabakar'},
//  {'email': 'bishalkumar8486@gmail.com',
//   'views': 'Aww,  Bishal! Thanks for your message. You’re truly one of the most amazing people I’ve met,  and I cherish every moment of our heartfelt talks!',
//   'user': 'Abhisha Shrivastava'},
//  {'email': 'bishalkumar8486@gmail.com',
//   'views': "Stay sweet and kind-hearted,  my friendo! Life will move on,  and don't complicate it by being so much philosophical ;)",
//   'user': 'Rithick Prabakar'},
//  {'email': 'ishangupta3210805@gmail.com',
//   'views': "Godfather of Data/ML but trying to seduce consulting (Sundar Pichai learnt ML under him,  that's why he doesn't know ML XD)",
//   'user': 'Ishan Gupta'},
//  {'email': 'lhariprasad21@gmail.com',
//   'views': 'Thank you to the super-sweet co-head,  dep mate and a great buddy for always being there and listening to my endless rant <3',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'reavigil0204@gmail.com',
//   'views': 'Coolest woman and the reason 3 other people graduated successfully',
//   'user': 'Aaditri Vaibhav'},
//  {'email': 'spectacularsam11@gmail.com',
//   'views': 'Kohleee,  Bhimsal this side,  thank you buddy for everything,  may our paths cross more often ahead so I can tell you complicated words ;)',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'saurav.raj5592@gmail.com',
//   'views': 'Photography and hairstyle inspiration. Best J partner.',
//   'user': 'Chirag Ghosh'},
//  {'email': 'tanishqmittal04@gmail.com',
//   'views': 'Thank you for traversing the KGP Journey with me from start to end...I hope you cherished our bond as much as I did.',
//   'user': 'Bishal Kumar Behera'},
//  {'email': 'vedantzope@gmail.com',
//   'views': 'He has is own systuum ahd he rolls pretty hard',
//   'user': 'Ishan Gupta'},
//  {'email': 'vedantzope@gmail.com',
//   'views': "The most peace maaro-fy person on Earth who's probably asleep right now.",
//   'user': 'Aaditri Vaibhav'},
//  {'email': 'aaditri.vaibhav@gmail.com',
//   'views': "The real question is what is the thing she can't do? Multitalented af!!",
//   'user': 'Ishan Gupta'},
//  {'email': 'anandashwini2514@gmail.com',
//   'views': 'Chotta packet bada dhamaka',
//   'user': 'Ishan Gupta'},
//  {'email': 'muskanpurohit01@gmail.com',
//   'views': 'FIRST OF ALL I MISSSS HER A LOTTTTT(CRI CRI).SHE IS MY RR,  FOOD,  GOSS PARTNER <3 AND STRANGELY OUR MUSIC TASTE IS HELLA SIMILAR(wordlimitwhyaaa)',
//   'user': 'SAMYUKTA KAGDELWAR'},
//  {'email': 'jean.setag@gmail.com',
//   'views': 'Hope you say yes and make me the happiest person in the world.\n\\nHJB Roll sapadalama?',
//   'user': 'Abilash B'},
//  {'email': 'sayan1996dutta@gmail.com',
//   'views': 'Gym Gym Gym',
//   'user': 'Shiva Kumar'},
//  {'email': 'rajasekharadapa@yahoo.com',
//   'views': 'Kattappa mahismati ka raksha nhi kr saka',
//   'user': 'Shiva Kumar'},
//  {'email': 'kavi.pradhap434@gmail.com',
//   'views': 'Kavi anna. Namaste!',
//   'user': 'Shiva Kumar'},
//  {'email': 'durvasulasaibhaskar@gmail.com',
//   'views': 'Just check with.',
//   'user': 'Shiva Kumar'},
//  {'email': 'balaaero1997@gmail.com',
//   'views': 'Bala Bala Bala... bla bla bla',
//   'user': 'Shiva Kumar'},
//  {'email': 'gaganlphome@gmail.com',
//   'views': 'KEM CHHO?',
//   'user': 'Shiva Kumar'},
//  {'email': 'bamreshmohanta@gmail.com',
//   'views': 'We also call him SHER because he eats only nonveg. Sher ke age koi kaise bol sakta hai',
//   'user': 'Akash Saha'},
//  {'email': 'hinakamdi75@gmail.com',
//   'views': 'Dance karooooooo . zingh zhing zghin',
//   'user': 'Akash Saha'},
//  {'email': 'akashsaha.dt@gmail.com',
//   'views': 'Great guy. Have a keen knowledge of dressing and fashion. Love you brother',
//   'user': 'Shaikh Azhar Mahebub'},
//  {'email': 'akashsaha.dt@gmail.com',
//   'views': 'real swagstar! banglar chele',
//   'user': 'Puja Saha'},
//  {'email': 'akashsaha.dt@gmail.com',
//   'views': 'brother is a superstar. real fan of puneet superstar.',
//   'user': 'Patel Varshidkumar Rakeshbhai'},
//  {'email': 'akashsaha.dt@gmail.com',
//   'views': 'Funky welcoming boy cum budding vlogger of our department. COOL DUDE INDEED & friend in need',
//   'user': 'Bishop Debnath'},
//  {'email': 'rahulpatel101999@gmail.com',
//   'views': 'from roommate to future jobmate. Partner in work and fun !',
//   'user': 'Akash Saha'},
//  {'email': 'saradiagspr@gmail.com',
//   'views': 'This girl is a crazy one. She does all her work on time. No deadlines to be hit. Great person to work with',
//   'user': 'Akash Saha'},
//  {'email': 'saradiagspr@gmail.com',
//   'views': 'Totally crazy but a real friend who loves and cares for you.',
//   'user': 'Akash Saha'},
//  {'email': 'sarthak.nakra@gmail.com',
//   'views': 'Chinta mat kar. Load mat le. All is well. (CHINTARAM in the house)',
//   'user': 'Akash Saha'},
//  {'email': 'satya.birla2017@gmail.com',
//   'views': 'Very funny guy LOL',
//   'user': 'Akash Saha'},
//  {'email': 'tejas976434@gmail.com',
//   'views': 'My gym and body building guide. GURUJI ka PYAR chahiye',
//   'user': 'Akash Saha'},
//  {'email': 'dr8231667@gmail.com',
//   'views': 'This might not seem much but I apologise for hurting u. U are one of the two first friends I have made in IIT. I wish we could be friends again.',
//   'user': 'Bidisha Biswas'},
//  {'email': 'bidishabiswas1995@gmail.com',
//   'views': 'Every moment with you has been special. I’m thankful for our connection and promise to be by your side as we continue this journey together.',
//   'user': 'Karhade Shubham Dilip'},
//  {'email': 'bidishabiswas1995@gmail.com',
//   'views': 'Always express your feelings and don\'t hide it? , Try to continue your "The Salman Khan" Walk???, You are a great friend,  person ?❤',
//   'user': 'Violina Gogoi'},
//  {'email': 'swarnality027@gmail.com',
//   'views': 'Charming,  glamourous,  epitome of beauty,  cute,  sweet,  and intelligent. Here we present you Ms. Calcutta. A friend in need and friend indeed.',
//   'user': 'Bishop Debnath'},
//  {'email': 'swarnality027@gmail.com',
//   'views': "We might not be close anymore,  but I'll always wish the best for you. I believe we are a lot alike,  that's why we parted. Sorry for hearting u.",
//   'user': 'Bidisha Biswas'},
//  {'email': 'sushmitaboro99@gmail.com',
//   'views': 'Embrace yourself,  and value the people around you. Do live life fully. There is so much goodness in the world,  focus on them. Be a little crazy.',
//   'user': 'Bidisha Biswas'},
//  {'email': 'parassaini247554@gmail.com',
//   'views': 'Badass chicha',
//   'user': 'Parv'},
//  {'email': 'akarshu7658@gmail.com',
//   'views': 'Ui ui ui... Saalonn...',
//   'user': 'Shiva Kumar'},
//  {'email': 'as.anshikagupta@gmail.com',
//   'views': 'From the very first day,  I have never seen you not being nice. Be a little selfish. And please keep being my friend?!',
//   'user': 'Bidisha Biswas'},
//  {'email': 'shivanisakat31@gmail.com',
//   'views': 'Best company to enjoy Springfest with...(iykyk)',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'oishikc98@gmail.com',
//   'views': 'Tez nahi jyada bhag,  Life ye marathon hai sprint nhi samjh baat. Mai rhyme me advice de rha Life Changing',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'adichinchkar@gmail.com',
//   'views': 'Highest in the room. Activist,  Environmentalist,  Nisarg Premi.',
//   'user': 'Abhinav Anand'},
//  {'email': 'heyparthpatel@gmail.com',
//   'views': 'DMs every professor; Believes in act now,  think later.',
//   'user': 'Abhinav Anand'},
//  {'email': 'rohitrtr97@gmail.com',
//   'views': 'A victim of bad Vastu; Owns a huge collection of unused fitness related stuff.',
//   'user': 'Abhinav Anand'},
//  {'email': 'sudheeer225@gmail.com',
//   'views': 'Coolest kid in the universe',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'sudheeer225@gmail.com',
//   'views': 'A pool champion with a 1-1 tournament record against me,  proving that his skills are as legendary as mine.',
//   'user': 'Abhinav Anand'},
//  {'email': 'ar.simrann@gmail.com',
//   'views': 'Most sober person ever met',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'shreyas1012singh@gmail.com',
//   'views': 'The Supreme CR. Smartest human being ever existed.',
//   'user': 'Ayushi Gupta'},
//  {'email': 'shreyas1012singh@gmail.com',
//   'views': 'CR ji ! Aapki baaton se hua influence,  jaise Ganga aur Jamuna ji ke confluence ! Rhyme karna mandatory nhi tha,  par dosti nibhana tha. Love u !',
//   'user': 'Oishik Chakraborty'},
//  {'email': 'tabatapu@gmail.com',
//   'views': 'यारों का यार,  बड़ा मज़ेदार',
//   'user': 'Sachan Shobhan Shailendra Anandeshwari'},
//  {'email': 'tabatapu@gmail.com',
//   'views': 'tapu is the best',
//   'user': 'Kyada Utsav Dipakbhai'},
//  {'email': 'tabatapu@gmail.com',
//   'views': 'Overqualified underachiever. Future CM of Arunachal Pradesh.',
//   'user': 'Abhinav Anand'},
//  {'email': 'abhi9now9@gmail.com',
//   'views': 'Bhai... bade hokr aapke jaisa banna hai',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'abhi9now9@gmail.com',
//   'views': 'वयस्क आदमी,  प्रेम का स्रोत',
//   'user': 'Sachan Shobhan Shailendra Anandeshwari'},
//  {'email': 'sachanshobhan@gmail.com',
//   'views': 'Leaves every place better.',
//   'user': 'Abhinav Anand'},
//  {'email': 'gayushi14@gmail.com',
//   'views': 'Young,  Dumb,  Cute kid.',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'mayankjha7@gmail.com',
//   'views': 'Real MC (Master of Ceremonies)',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'saipuneethdamarla@gmail.com',
//   'views': 'Hello Mr. Professor Jr.\n\\nVery grateful for your help whenever i was in need.',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'aishwaryashyam007@gmail.com',
//   'views': "When she's around,  expect: heavy rains,  network issues,  flat tires; do not expect: a good bargain,  unniyappams.",
//   'user': 'Abhinav Anand'},
//  {'email': 'harieshrg@gmail.com',
//   'views': 'Needs to get some sleep.',
//   'user': 'Abhinav Anand'},
//  {'email': 'bhattrohit1997@gmail.com',
//   'views': 'वयस्क आदमी,  सम्मानजनक जीवन का आधार',
//   'user': 'Sachan Shobhan Shailendra Anandeshwari'},
//  {'email': 'architectsakshi05@gmail.com',
//   'views': 'Hiiii Sakshiiiii\n\\nKaisi hai????\n\\n.\n\\n.\n\\n.',
//   'user': 'Shreyas Pratap Singh'},
//  {'email': 'abhishekkmr638@gmail.com',
//   'views': "To the friend who's always a text away. It's never a dull moment with you. Grateful for your presence and our friendship. Love and best wishes?",
//   'user': 'Sneha Roy'},
//  {'email': 'siddheshsaigaonkar4@gmail.com',
//   'views': 'Great time with you buddy!!',
//   'user': 'Hritik Sachan'},
//  {'email': 'jk8126582813@gmail.com',
//   'views': 'Dedicated dost I ever seen',
//   'user': 'Rajat Biswas'},
//  {'email': 'satyaprakash20121998@gmail.com',
//   'views': 'hello',
//   'user': 'Prateek Kumar Amrawanshi'},
//  {'email': 'cyan4568@gmail.com',
//   'views': 'basically about memories during our department photoshoot #Aprilphotoshoot #Chemical Engineering #iitkgp',
//   'user': 'Cyan Mukherjee'},
//  {'email': 'chanchal2ksharma@gmail.com',
//   'views': 'Best mother of the group one can ask for!',
//   'user': 'Shohinee Das'},
//  {'email': 'chanchal2ksharma@gmail.com',
//   'views': "Her character is just as her name suggests. I'm fortunate to have you as my friend",
//   'user': 'Chauhan Aman Ashok'},
//  {'email': 'nourivizag@gmail.com',
//   'views': 'Best person to sit at midnight and talk about your existential crisis! <3',
//   'user': 'Shohinee Das'},
//  {'email': 'nourivizag@gmail.com',
//   'views': 'Growing seed/plant in the group',
//   'user': 'Chanchal Sharma'},
//  {'email': 'amanc10079@gmail.com',
//   'views': 'Will annoy you to death but also come to your rescue ASAP',
//   'user': 'Shohinee Das'},
//  {'email': 'amanc10079@gmail.com',
//   'views': 'Nutrition guide in the group.. Oops Gyaani Baba',
//   'user': 'Chanchal Sharma'},
//  {'email': 'ifzalhussain456@gmail.com',
//   'views': 'Thailand ki GF,  iPad,  Mackbook.... Mehnge sapne dekhta tha apna bhai',
//   'user': 'Shiva Kumar'},
//  {'email': 'shohinee0309@gmail.com',
//   'views': 'Dosto ka Doremon',
//   'user': 'Chanchal Sharma'},
//  {'email': 'shohinee0309@gmail.com',
//   'views': 'Apni Bengali foodie. You should be happy that I did not upload your resting bitch face.',
//   'user': 'Chauhan Aman Ashok'},
//  {'email': 'gurpreetsinghpaul320@gmail.com',
//   'views': 'Akshay ka bra,  filechor ki chori,  teesri taang etc. sab pr dhyan deta tha',
//   'user': 'Shiva Kumar'},
//  {'email': 'abilashbabu470@gmail.com',
//   'views': 'Meeting Abilash and OG was like finding the last slice of pizza—unexpected and amazing. College wouldn’t have been the same without them!',
//   'user': 'Rachana K'},
//  {'email': 'abilashbabu470@gmail.com',
//   'views': 'Never ever said no for a CHAI....CHAIMATE',
//   'user': 'Elambaruthi E'},
//  {'email': 'paruthi1796@gmail.com',
//   'views': 'Elambaruthi is a true GENTLEMAN —always stepping up to help and support.',
//   'user': 'Rachana K'},
//  {'email': 'thegreataditya.1999@gmail.com',
//   'views': 'Hello',
//   'user': 'Raj Shekhar Vaghela'},
//  {'email': 'sonuishwarprasad@gmail.com',
//   'views': 'Hello sonu',
//   'user': 'Raj Shekhar Vaghela'},
//  {'email': 'chandrahaas3@gmail.com',
//   'views': 'Areyy entraaaaa...!!!',
//   'user': 'Akula Vara Durga Siva Sai'},
//  {'email': 'charankumariiitn@gmail.com',
//   'views': 'Hii anniya',
//   'user': 'Duddu Chandrahaas'},
//  {'email': 'amalendu.prb@gmail.com',
//   'views': 'Walking Wikipedia!',
//   'user': 'Amalendu Das'},
//  {'email': 'imadilraza104@gmail.com',
//   'views': 'Amazing husband',
//   'user': 'Mridul Chawla'},
//  {'email': 'imadilraza104@gmail.com',
//   'views': 'Amazing wife',
//   'user': 'Mridul Chawla'},
//  {'email': 'imadilraza104@gmail.com',
//   'views': 'Shayari likhta hu rat bhar,  sota rehta hu dinbhar',
//   'user': 'Pritam Das Kashyap'},
//  {'email': 'mridul.chawla2405@gmail.com',
//   'views': "Testing, testing, 1-2-3! You're amazing, don't you see? Just a reminder, you got this! ?",
//   'user': 'Md Adil Raza'},
//  {'email': 'mridul.chawla2405@gmail.com',
//   'views': 'Badminton->Free Food->Sleep>Repeat',
//   'user': 'Pritam Das Kashyap'},
//  {'email': 'pritamkashyapdas98@gmail.com',
//   'views': 'VP sahab (SEG)',
//   'user': 'Mridul Chawla'},
//  {'email': 'pritamkashyapdas98@gmail.com',
//   'views': "Testing, testing, 1-2-3! You're amazing, don't you see? Just a reminder, you got this! ?",
//   'user': 'Md Adil Raza'},
//  {'email': 'charakash1700@gmail.com',
//   'views': 'Hellllooooo Mr....this is serious business..?',
//   'user': 'Paromita Pal'},
//  {'email': 'charakash1700@gmail.com',
//   'views': 'Ritanuka digger!',
//   'user': 'Amalendu Das'},
//  {'email': 'deepd9949@gmail.com',
//   'views': 'Dharer taka gulo maf kore de vai',
//   'user': 'Amalendu Das'},
//  {'email': '2002paromitapal@gmail.com',
//   'views': 'Kaaner gorai dorkar tor akta',
//   'user': 'Indranil Paul'},
//  {'email': '2002paromitapal@gmail.com',
//   'views': "From teaching me before skb's exam to making ppt for me,  thank you for everything.Wish u the best for ur future.U will be missed.Stay in touch?",
//   'user': 'Akash Char'},
//  {'email': 'palpartha066@gmail.com',
//   'views': 'Hiiii..... Noble leader Parthaaaa...❤️? Will miss your CRship ?',
//   'user': 'Paromita Pal'},
//  {'email': 'sameerkumarmahankuda647@gmail.com',
//   'views': 'O Sameer,  tatte kaun bujhjhi bara aachchi ?. #chhore maglu ke kut deve jaha dikhe!!',
//   'user': 'Raghubeer Rai'},
//  {'email': 'bhagabats098@gmail.com',
//   'views': 'I will never regret those wasted times with you. You have taught me so much! I wish you nothing but the best for future.',
//   'user': 'Divyajyoti Divyaranjan Rana'},
//  {'email': 'satyamkahali96@gmail.com',
//   'views': 'We laughed until we had to cry,  we loved right down to our last goodbye,  we were the best.',
//   'user': 'Divyajyoti Divyaranjan Rana'},
//  {'email': 'violinagogoi@gmail.com',
//   'views': "You don't always need to keep a strong font. Accept your weaknesses. Build your life for yourself. Miss you large cycle wala gussawali ladki.",
//   'user': 'Bidisha Biswas'},
//  {'email': 'karhadeshubham8@gmail.com',
//   'views': "I'm thankful to destiny for letting me meet u. I enjoyed every moment wth u on the campus. I know lyf will not be the same but pls be by my side",
//   'user': 'Bidisha Biswas'},
//  {'email': 'karhadeshubham8@gmail.com',
//   'views': 'I will never forget these times with you my dear ex roomie. I wish you nothing but the best,  be in touch.',
//   'user': 'Divyajyoti Divyaranjan Rana'},
//  {'email': 'snehroy@gmail.com',
//   'views': 'Met at one of the coursework classes and clicked from there. Ever since that',
//   'user': 'Maithilee'},
//  {'email': 'snehroy@gmail.com',
//   'views': 'The first girl I met on the campus,  now leaving with a friend for life. We met only a few times,  yet you were a constant part of my journey.',
//   'user': 'Abhishek Kumar'},
//  {'email': 'snehroy@gmail.com',
//   'views': 'Sneha is a delightful and active young woman,  a considerate friend,  and someone who embodies the qualities of a great HR professional.',
//   'user': 'Arjun Prakash'},
//  {'email': 'risim90s@gmail.com',
//   'views': 'A PERSON WHO WORKS MORE THAN THE DIRECTOR OF IIT KHARAGPUR',
//   'user': 'Rohit Kumar'},
//  {'email': 'sksuryawanshi1969@gmail.com',
//   'views': 'khana nehi khaata aur BC roy Jaata,  Sui lagataaa',
//   'user': 'Akash Saha'},
//  {'email': 'anshiarora910@gmail.com',
//   'views': 'My bestie.. from all the fights to laughters,  morning skin care to nigh strolls and food adventures.. u made this journey complete.',
//   'user': 'Meetali Garg'},
//  {'email': 'dushyantdixit90121@gmail.com',
//   'views': 'The most bakchod person on Earth.. Thank you for laughter and cries,  memories and learnings.',
//   'user': 'Meetali Garg'},
//  {'email': 'meetaligarg12@gmail.com',
//   'views': 'Ek achii dostii ke liye thank you. Bhot mzaa aaya 2 saal me or tere bina event feeka feeka sa lgta h,  you are just like  masala to our maggi??',
//   'user': 'Ritu Gupta'},
//  {'email': 'meetaligarg12@gmail.com',
//   'views': "Kehna to bhot hai but I don't find the right words,  so I just want to say thank you for everything in this kgp journey,  dragon ??",
//   'user': 'Rohit Kumar Kundu'},
//  {'email': 'naveenvikramsingh80@gmail.com',
//   'views': 'Thank You for always being there for me.. the most bakchod,  serious and pure hearted guy.',
//   'user': 'Meetali Garg'},
//  {'email': 'sehrawatparul10@gmail.com',
//   'views': 'At times childish,  at others sage-like.. tere husn ka jaadu hamesha yaad rahega?.. will meet you soon on your shaadi bro?',
//   'user': 'Meetali Garg'},
//  {'email': 'prosendasrs@gmail.com',
//   'views': "I've never had a male friend like you. Whenever you need assistance,  don't hesitate to reach out—I'll always do my best to be there for you.",
//   'user': 'Poulabi Ghosh'},
//  {'email': 'rohitkumarkundu@gmail.com',
//   'views': 'Best human walking on Earth.. most helpful and caring.. tere bina mere kya hi hota?.. tension mat le tuje nhi bhulungi mai',
//   'user': 'Meetali Garg'},
//  {'email': 'arghyadeep.ng@gmail.com',
//   'views': 'Such a amazing friend.The puchka makker. Can discuss anything anytime . Thanks for sharing a good time',
//   'user': 'Subhransu Kumar Negi'},
//  {'email': 'arghyadeep.ng@gmail.com',
//   'views': 'An amazing friend . Our beloved Jhonty Rhodes. Cheers to all the memories !',
//   'user': 'Subhransu Kumar Negi'},
//  {'email': 'arghyadeep.ng@gmail.com',
//   'views': 'An amazing friend .Our beloved Jonty Rhodes. Cheers to all the lovely memories !',
//   'user': 'Subhransu Kumar Negi'},
//  {'email': 'arghyadeep.ng@gmail.com',
//   'views': 'Thanks for being an amazing friend! Got your back always,  no matter what.',
//   'user': 'Atish Das'},
//  {'email': 'abja.ind@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this IIT journey not just wonderful but truly unforgettable',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'sachinsinghim@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this IIT journey wonderful & unforgettable.',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'subhransukumar99@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this journey so wonderful and memorable.',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'shivanichhipa66@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this IIT journey not just wonderful but truly unforgettable',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'khawashkr19@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this IIT journey not just wonderful but truly unforgettable.',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'arpanmett18@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this IIT journey not just wonderful but truly unforgettable.',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'atishdas2@gmail.com',
//   'views': 'I am so lucky to have had a friend like you who made this IIT journey not just wonderful but truly unforgettable.',
//   'user': 'Arghyadeep Nag'},
//  {'email': 'atishdas2@gmail.com',
//   'views': "Life is a Test match, not a T20; there's always a second innings to comeback.",
//   'user': 'Arghyadeep Nag'},
//  {'email': 'ritugupta030901@gmail.com',
//   'views': 'Our mommy dearest.. thank you for always pushing us in the right direction.. will miss your scoldings.',
//   'user': 'Meetali Garg'},
//  {'email': 'physics.suman7@gmail.com',
//   'views': 'The most wise',
//   'user': 'Meetali Garg'},
//  {'email': 'swapmedas@gmail.com',
//   'views': 'Hamara Neta kaisa ho? Swapnil bhai jaisa ho.',
//   'user': 'Shiva Kumar'},
//  {'email': 'manojchahar477@gmail.com', 'views': 'Hi', 'user': 'Rounak'},
//  {'email': 'pubali369@gmail.com',
//   'views': 'You appeared on campus, invisible yet unforgettable. From night rides to near-accidents, we reunited for a lifetime miracle. Forever grateful.',
//   'user': 'Ajay Kumar Tete'},
//  {'email': 'pubali369@gmail.com',
//   'views': 'You appeared on campus,invisible yet unforgettable. From night rides to near accidents,we reunited for a lifetime miracle.Forever grateful.',
//   'user': 'Ajay Kumar Tete'},
//  {'email': 'pubali369@gmail.com',
//   'views': 'You appeared on campus,  invisible yet unforgettable. From night rides to near-accidents,  we reunited for a lifetime miracle. Forever grateful.',
//   'user': 'Ajay Kumar Tete'},
//  {'email': 'sanmatishastrijain@gmail.com',
//   'views': 'Gowardhan ghee kha raha na bhai?',
//   'user': 'Shiva Kumar'}]

let demoData=[{'email': 'yash.gupta.18.06.03@gmail.com',
  'views': "I am very lucky to have met you in my 1st week on campus...cuz I can't imagine surviving here without you for more than 10 days EVER!!!",
  'user': 'Sakshi Kaushal'},{'email': 'yash.gupta.18.06.03@gmail.com',
    'views': "I am very lucky to have met you in my 1st week on campus...cuz I can't imagine surviving here without you for more than 10 days EVER!!!",
    'user': 'Sakshi Kaushal'},
    {'email': 'yash.gupta.18.06.03@gmail.com',
      'views': "I am very lucky to have met you in my 1st week on campus...cuz I can't imagine surviving here without you for more than 10 days EVER!!!",
      'user': 'Sakshi Kaushal'},
      {'email': 'rsahookgp@gmail.com',
        'views': "I am very lucky to have met you in my 1st week on campus...cuz I can't imagine surviving here without you for more than 10 days EVER!!!",
        'user': 'Sakshi Kaushal'},
]
  
mongoose
  .connect("mongodb://localhost:27017/local", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("Connected to MongoDB successfully!");

    app.listen(5000, () => {
      console.log("Server is running on port 5000");
    });
  })
  .catch((error) => {
    console.error("Error connecting to MongoDB:", error);
  });
for (let i=0;i<demoData.length;i++){
  console.log(demoData[i].email)
}
for (let i = 0; i < demoData.length; i++) {
  let email = demoData[i].email;

  // Create a user_msg array for demoData[i]
  demoData[i].user_msg = [];

  for (let j = 0; j < demoData.length; j++) {
    if (demoData[j].email === email) {
      // Add the message and user info to user_msg for matching emails
      let dict = { msg: demoData[j].views, user: demoData[j].user};
      demoData[i].user_msg.push(dict);
    }
  }

  // Remove the current email from demoData array if it is a duplicate
  demoData = demoData.filter(
    (item, index, self) =>
      self.findIndex((t) => t.email === item.email) === index ||
      item.email !== email
  );
}

console.log(demoData);

var nodemailer = require("nodemailer");
var transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: "yearbookandclass.song.2024@gmail.com",
    pass: "hghkgkkqebbuishu",
  },
});
for (let i = 0; i < demoData.length; i++) {
    var mailOptions = {
    from: "yearbookandclass.song.2024@gmail.com",
    to: demoData[i].email,
    subject: "Testimonial",
    html: `
        <p><strong>Greetings from Students' Alumni Cell, IIT Kharagpur!
</strong></p>
        <p>Congratulations on completing your incredible journey at IIT Kharagpur. As you embark on the next chapter of your life, we want to celebrate your dedication and perseverance. IIT KGP is where acquaintances grow into family and lifelong connections are forged. To commemorate this milestone, we’ve attached heartfelt testimonials from your batchmates, filled with admiration and gratitude to remind you of the cherished bonds and memories you’ve created here. As you reflect on this transformative chapter, we hope it fills you with pride and joy for the friendships and experiences that shaped your journey.</p><br>
       
     
<table style="border: 2px solid black;border-top:none; border-collapse: collapse; width: 100%; margin-top: 20px;">
   <th style="background-color: #f2f2f2;">
     <tr>
       <th style="border: 2px solid black; padding: 8px; text-align: center;font-size:15px">Comments</th>
       <th style="border: 2px solid black; padding: 8px; text-align: center;font-size:15px">User</th>
     </tr>
   </th>
   <tbody>
   ${
    demoData[i].user_msg.map((item)=>(
       `<tr>
        <td style="border: 2px solid black; padding: 8px;">${item.msg}</td>
        <td style="border: 2px solid black; padding: 8px;text-align: center;">${item.user}</td>
      </tr>`
    )).join('')
   }
      
   </tbody>
 </table>
  <p><strong>Wishing you success in all your future endeavors, and we encourage you to stay connected with your alma matter.</strong></p><br>
<div style="display: flex; align-items: center;transform: translateY(60px);margin:30px">
      
      <img src="cid:image1" alt="IIT Kharagpur" style="width:250px; margin-right: 10px;">
      
      
      <div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.5;">
        <h1 style="margin: 0; font-size: 18px;">Rupesh Sahoo</h1>
        <h3 style="margin: 0; font-size: 14px;">Second Year UG | <span>Department of Electrical Engineering</span></h3>
        <h3 style="margin: 0; font-size: 14px;">Web Team Member | <span>Students' Alumni Cell</span></h3>
        <p style="margin: 0;">Office of Alumni Affairs</p>
        <a href="https://www.iitkgp.ac.in" style="color:rgb(12,12,12)">IIT Kharagpur</a>
        <p style="margin: 0;">+91 9078260658</p>
        <p style="margin: 0;color:rgb(12,12,12)">rsahookgp@gmail.com</p>
        <a href="https://www.linkedin.com/in/rupesh-sahoo-384285306/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app" 
           style="color:rgb(12,12,12); text-decoration: none;">LinkedIn</a>
      </div>
    </div>
  `,
  attachments: [
    {
      filename: "iit-logo.png", 
      path: "./iit_kharagpur123.jpg", 
      cid: "image1", 
    },
  ],
};
 


 

  
  transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error);
    } else {
      console.log("mail sent " + info);
    }
  });
}


